version: "3.9"
services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8000:5000"
    environment:
      - POSTGRES_DB=db
  db:
    image: "postgres:latest"
    container_name: db
    restart: always

    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

